version: '3.8'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --no-audit --no-fund && npm run dev"
    ports:
      - '5173:5173'
