name: Build and Deploy (Vercel + Render)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build frontend
        run: |
          cd frontend
          npm ci --no-audit --no-fund
          npm run build
      - name: Deploy to Vercel (if configured)
        if: env.VERCEL_TOKEN != '' || secrets.VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod --confirm --cwd frontend
      - name: Trigger Render deploy (if configured)
        if: secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": true}'
